name: Update NCAA Predictions CSV

on:
  schedule:
    - cron: '0 10,17 * * *' # Runs at 10 AM and 5 PM Eastern Time daily
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Download the CSV file
      - name: Download NCAA Predictions CSV
        run: |
          curl -o ncaapredictions.csv https://www.thepredictiontracker.com/ncaapredictions.csv

      # Add timestamp to filename and move to data folder
      - name: Add Timestamp and Move CSV
        run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          mkdir -p data
          mv ncaapredictions.csv "data/ncaapredictions_$timestamp.csv"

      # Check if CSV content has changed (optional, to avoid unnecessary commits)
      - name: Check CSV Changes
        id: check-csv
        run: |
          git diff --exit-code --quiet data/ncaapredictions_*.csv || echo "DIFFERENT_CSV=true" >> $GITHUB_ENV

      # Commit and push changes
      - name: Commit and Push Changes
        if: env.DIFFERENT_CSV == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          timestamp=$(date +'%Y%m%d_%H%M%S')
          branch_name="update-csv-$timestamp"
          git checkout -b "$branch_name"
          git add data/ncaapredictions_*.csv
          git commit -m "Update NCAA predictions CSV with timestamp $timestamp"
          git push origin "$branch_name"
          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main
          git push origin --delete "$branch_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
